version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: e2e/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CI=true
      - BROWSER=none

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    depends_on:
      - app
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: "2g"
